#!/usr/bin/env python3
"""Regenerate testdata/expected.json from the reference tiktoken implementation.

The Go tests never call Python; they assert against the committed expected.json.
This script is what makes that file trustworthy, and CI runs it with --check so
the committed answers cannot drift away from real tiktoken.

Usage:
    python3 scripts/gen_expected.py            # rewrite testdata/expected.json
    python3 scripts/gen_expected.py --check    # fail if it would change
"""

import argparse
import difflib
import json
import pathlib
import sys

try:
    import tiktoken
except ImportError:
    sys.exit("tiktoken is not installed: pip install tiktoken")

ROOT = pathlib.Path(__file__).resolve().parent.parent
CORPUS = ROOT / "testdata" / "corpus.json"
EXPECTED = ROOT / "testdata" / "expected.json"


def raw_bytes(case):
    """A case carries either readable `text` or explicit `hex` for raw bytes."""
    if ("text" in case) == ("hex" in case):
        sys.exit(f"case {case['name']!r}: need exactly one of 'text' or 'hex'")
    if "text" in case:
        return case["text"].encode("utf-8")
    return bytes.fromhex(case["hex"])


def build():
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))
    enc = tiktoken.get_encoding(corpus["encoding"])

    cases = {}
    for case in corpus["cases"]:
        data = raw_bytes(case)
        try:
            text = data.decode("utf-8")
            valid = True
        except UnicodeDecodeError:
            # What any JSON/HTTP client would put on the wire. Each maximal
            # invalid subpart collapses to one U+FFFD.
            text = data.decode("utf-8", errors="replace")
            valid = False
        # disallowed_special=() so "<|endoftext|>" counts as the literal text
        # a user actually typed, which is what these tools are asked about.
        ids = enc.encode(text, disallowed_special=())
        cases[case["name"]] = {
            "valid_utf8": valid,
            "decoded_hex": text.encode("utf-8").hex(),
            "tokens": len(ids),
            "ids": ids,
        }

    return {
        "_comment": "GENERATED by scripts/gen_expected.py -- do not edit by hand.",
        "encoding": corpus["encoding"],
        "tiktoken_version": tiktoken.__version__,
        "cases": cases,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches tiktoken; do not write")
    args = ap.parse_args()

    new = json.dumps(build(), indent=2, ensure_ascii=False) + "\n"

    if not args.check:
        EXPECTED.write_text(new, encoding="utf-8")
        print(f"wrote {EXPECTED.relative_to(ROOT)}")
        return 0

    if not EXPECTED.exists():
        sys.exit(f"{EXPECTED.relative_to(ROOT)} is missing; run without --check")
    old = EXPECTED.read_text(encoding="utf-8")
    if old == new:
        print(f"{EXPECTED.relative_to(ROOT)} matches tiktoken {tiktoken.__version__}")
        return 0

    sys.stdout.writelines(difflib.unified_diff(
        old.splitlines(keepends=True), new.splitlines(keepends=True),
        fromfile="committed", tofile="tiktoken", n=2))
    sys.exit("\nexpected.json no longer matches tiktoken; "
             "rerun scripts/gen_expected.py and review the diff")


if __name__ == "__main__":
    sys.exit(main())
